
/**
 * AUTO-GENERATED FILE @ Sun, 10 Mar 2024 19:46:27 GMT - DO NOT EDIT!
 *
 * This file was automatically generated by schemats v.1.0.5
 * $ schemats generate postgres://username:password@34.79.81.42:5432/group6 -s public
 *
 */



export interface User { 
  id: number
  first_name?: string | null
  last_name?: string | null
  email: string
  password: string
  created_by?: string | null
  created_date: Date
  updated_by?: string | null
  updated_date: Date 
}

export interface Task { 
  id: number
  title: string
  description: string
  due_date?: Date | null
  priority?: string | null
  status?: string | null
  user_id: number
  category_id: number
  created_by?: string | null
  created_date: Date
  updated_by?: string | null
  updated_date: Date 
}

export interface Migrations { 
  id: number
  name: string
  run_on: Date 
}

export interface Category { 
  id: number
  name: string
  color?: string | null
  icon?: string | null
  user_id: number
  created_by?: string | null
  created_date: Date
  updated_by?: string | null
  updated_date: Date 
}

export interface Tables {
  user: User,
  task: Task,
  migrations: Migrations,
  category: Category
}