CREATE TABLE public.user (
  id              INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name      TEXT,
  last_name       TEXT,
  email           TEXT NOT NULL UNIQUE,
  password        TEXT NOT NULL,
  created_by      TEXT DEFAULT 'system',
  created_date    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_by      TEXT DEFAULT 'system',
  updated_date    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
)

